### PR TITLE
Fix tests and make them fast.

### LINKED ISSUE #417: fix up tests in `config_test.go`

### LINKED ISSUE #422: tests currently export... consider changing how those run bc otherwise they need to wait for timeout

### LINKED ISSUE #423: map[string]string doesn't work for headers or resource attributes. Use string types, and separately split them as key value pairs

### PR DESCRIPTION
**Pull request by kentquirk**
In service of making tests run correctly as well as quickly, I ended up making changes to functionality and also creating a test harness.

Sadly, I also spent a lot of time shutting up an aggressive linter. I didn't get it all, but it doesn't matter yet.

Fixes #417
Fixes #422 
Fixes #423

### CODE REVIEW

File: launcher/config_test.go [hunk 1]
```diff
@@ -72,8 +78,58 @@ func (logger *testLogger) requireNotContains(t *testing.T, expected string) {
...
-func (logger *testLogger) reset() {
-	logger.output = nil
+// Create some dummy server implementations so that we can
+// spin up tests that don't need to wait for a timeout trying to send data.
+type dummyTraceServer struct {
+	collectortrace.UnimplementedTraceServiceServer
+}
+
+func (*dummyTraceServer) Export(ctx context.Context, req *collectortrace.ExportTraceServiceRequest) (*collectortrace.ExportTraceServiceResponse, error) {
+	fmt.Println("inside trace export", time.Now().Format(time.RFC3339))
```
Comment (MikeGoldsmith) [inline launcher/config_test.go:88]: nit: these log lines can be removed

File: launcher/config_test.go [hunk 2]
```diff
@@ -72,8 +78,58 @@ func (logger *testLogger) requireNotContains(t *testing.T, expected string) {
...
+	return &collectortrace.ExportTraceServiceResponse{}, nil
+}
+
+type dummyMetricsServer struct {
+	collectormetrics.UnimplementedMetricsServiceServer
+}
+
+func (*dummyMetricsServer) Export(ctx context.Context, req *collectormetrics.ExportMetricsServiceRequest) (*collectormetrics.ExportMetricsServiceResponse, error) {
+	fmt.Println("inside metrics export", time.Now().Format(time.RFC3339))
```
Comment (MikeGoldsmith) [inline launcher/config_test.go:97]: nit: these log lines can be removed

File: launcher/config_test.go [hunk 3]
```diff
@@ -72,8 +78,58 @@ func (logger *testLogger) requireNotContains(t *testing.T, expected string) {
...
+}
+
+// dummyGRPCListener is a test helper that builds a dummy grpc server that does nothing but
+// returns quickly so that we don't have to wait for timeouts
+func dummyGRPCListener() func() {
+	grpcServer := grpc.NewServer()
+	collectortrace.RegisterTraceServiceServer(grpcServer, &dummyTraceServer{})
+	collectormetrics.RegisterMetricsServiceServer(grpcServer, &dummyMetricsServer{})
+
+	// we need to listen on localhost, not 0.0.0.0, to satisfy JAMF without causing problems
```
Comment (MikeGoldsmith) [inline launcher/config_test.go:108]: This is an dev env specific thing, could we remove this comment as it could be misleading to overs?

File: launcher/config_test.go [hunk 4]
```diff
@@ -72,8 +78,58 @@ func (logger *testLogger) requireNotContains(t *testing.T, expected string) {
...
+// withTestExporters conforms to the Option interface and sets up the options needed
+// to prevent a test from having to time out. It won't work unless the test also does this:
+//
+// stopper := dummyGRPCListener()
+// defer stopper()
+//
+// This is a convenience function.
+func withTestExporters() Option {
+	return func(c *Config) {
+		WithSpanExporterEndpoint("localhost:4317")(c)
```
Comment (MikeGoldsmith) [inline launcher/config_test.go:128]: The launcher should default to export to `localhost:4317`. It's fine to have them explicit here, but just making the note.

File: launcher/config_test.go [hunk 5]
```diff
@@ -125,20 +181,19 @@ func TestMetricEndpointDisabled(t *testing.T) {
...
-	logger.reset()
+	// in order for tests to not have to timeout during
+	// the shutdown call, we must direct them to a running
+	// server, which means that it has to go to localhost:4317,
+	// and it must be Insecure.
+	stopper := dummyGRPCListener()
+	defer stopper()
 
-	shutdown, _ = ConfigureOpenTelemetry(
+	fmt.Println("before config", time.Now().Format(time.RFC3339))
```
Comment (MikeGoldsmith) [inline launcher/config_test.go:192]: nit: more debug log entries

File: launcher/config_test.go [hunk 6]
```diff
@@ -182,8 +236,8 @@ func TestInvalidMetricsPushIntervalConfig(t *testing.T) {
 	shutdown, _ := ConfigureOpenTelemetry(
 		WithLogger(logger),
 		WithServiceName("test-service"),
-		WithSpanExporterEndpoint("127.0.0.1:4000"),
-		WithMetricExporterEndpoint("127.0.0.1:4000"),
+		WithSpanExporterEndpoint("localhost:4317"),
```
Comment (MikeGoldsmith) [inline launcher/config_test.go:239]: Can we use `WithTestExporters` here too?

**Review by MikeGoldsmith — APPROVED** [review]
Looks great, thanks @kentquirk. I've add some clean-up suggestions, none are pressing and could be fixed later 👍🏻 

The linter is super aggressive!  eg enforcing comments end with a `.` 😬
